// All 47 counties of Kenya
export const KENYA_COUNTIES = [
  "Baringo", "Bomet", "Bungoma", "Busia", "Elgeyo-Marakwet",
  "Embu", "Garissa", "Homa Bay", "Isiolo", "Kajiado",
  "Kakamega", "Kericho", "Kiambu", "Kilifi", "Kirinyaga",
  "Kisii", "Kisumu", "Kitui", "Kwale", "Laikipia",
  "Lamu", "Machakos", "Makueni", "Mandera", "Marsabit",
  "Meru", "Migori", "Mombasa", "Murang'a", "Nairobi",
  "Nakuru", "Nandi", "Narok", "Nyamira", "Nyandarua",
  "Nyeri", "Samburu", "Siaya", "Taita-Taveta", "Tana River",
  "Tharaka-Nithi", "Trans-Nzoia", "Turkana", "Uasin Gishu",
  "Vihiga", "Wajir", "West Pokot"
];

// County images stored locally
export const COUNTY_IMAGES: Record<string, string> = {
  "Baringo": "/images/counties/baringo.jpg",
  "Bomet": "/images/counties/bomet.jpg",
  "Bungoma": "/images/counties/bungoma.jpg",
  "Busia": "/images/counties/busia.jpg",
  "Elgeyo-Marakwet": "/images/counties/elgeyo-marakwet.jpg",
  "Embu": "/images/counties/embu.jpg",
  "Garissa": "/images/counties/garissa.jpg",
  "Homa Bay": "/images/counties/homa-bay.jpg",
  "Isiolo": "/images/counties/isiolo.jpg",
  "Kajiado": "/images/counties/kajiado.jpg",
  "Kakamega": "/images/counties/kakamega.jpg",
  "Kericho": "/images/counties/kericho.jpg",
  "Kiambu": "/images/counties/kiambu.jpg",
  "Kilifi": "/images/counties/kilifi.jpg",
  "Kirinyaga": "/images/counties/kirinyaga.jpg",
  "Kisii": "/images/counties/kisii.jpg",
  "Kisumu": "/images/counties/kisumu.jpg",
  "Kitui": "/images/counties/kitui.jpg",
  "Kwale": "/images/counties/kwale.jpg",
  "Laikipia": "/images/counties/laikipia.jpg",
  "Lamu": "/images/counties/lamu.jpg",
  "Machakos": "/images/counties/machakos.jpg",
  "Makueni": "/images/counties/machakos.jpg",
  "Mandera": "/images/counties/mandera.jpg",
  "Marsabit": "/images/counties/marsabit.jpg",
  "Meru": "/images/counties/meru.jpg",
  "Migori": "/images/counties/migori.jpg",
  "Mombasa": "/images/counties/mombasa.jpg",
  "Murang'a": "/images/counties/muranga.jpg",
  "Nairobi": "/images/counties/nairobi.jpg",
  "Nakuru": "/images/counties/nakuru.jpg",
  "Nandi": "/images/counties/nandi.jpg",
  "Narok": "/images/counties/narok.jpg",
  "Nyamira": "/images/counties/nyamira.jpg",
  "Nyandarua": "/images/counties/nyandarua.jpg",
  "Nyeri": "/images/counties/nyeri.jpg",
  "Samburu": "/images/counties/samburu.jpg",
  "Siaya": "/images/counties/siaya.jpg",
  "Taita-Taveta": "/images/counties/taita-taveta.jpg",
  "Tana River": "/images/counties/tana-river.jpg",
  "Tharaka-Nithi": "/images/counties/tharaka-nithi.jpg",
  "Trans-Nzoia": "/images/counties/trans-nzoia.jpg",
  "Turkana": "/images/counties/turkana.jpg",
  "Uasin Gishu": "/images/counties/uasin-gishu.jpg",
  "Vihiga": "/images/counties/vihiga.jpg",
  "Wajir": "/images/counties/wajir.jpg",
  "West Pokot": "/images/counties/west-pokot.jpg",
};

// All 47 counties featured on the index page
export const FEATURED_COUNTIES = [...KENYA_COUNTIES];
